#pragma config(Sensor, S1,     touchSensor,              sensorTouch)
#pragma config(Sensor, S2,     compassSensor,            sensorVirtualCompass)
#pragma config(Sensor, S3,     lightSensor,              sensorLightActive)
#pragma config(Sensor, S4,     sonarSensor,              sensorSONAR)
#pragma config(Motor,  motorA,          gripperMotor,       tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  motorB,          rightMotor,         tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  motorC,          leftMotor,          tmotorNormal, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
// This is for the NXT model, not TETRIX

//Line runner 2, rem bot, Companion tables 2.24

int i;
int j;
int threshold = 65;

//move foward to line in number sequence based on the parameter lineCount
void fowardToLine(int lineCount)
{

	for (i = 1; i <= lineCount; i++)
	{
		while (SensorValue[lightSensor] > threshold)
		{
			motor[rightMotor] = 60;
			motor[leftMotor] = 60;
		}
		//stop
		motor[rightMotor] = 0;
		motor[leftMotor] = 0;
		wait1Msec(500);
		//move just in front of the line to reset threshold below 65
		motor[rightMotor] = 60;
		motor[leftMotor] = 60;
		wait1Msec(600);
		//stop
		motor[rightMotor] = 0;
		motor[leftMotor] = 0;
		wait1Msec(500);

	}

}

//move back to starting position from any line position
void moveBack()
{
	while (nMotorEncoder[rightMotor] > 0)
	{
		motor[rightMotor] = -60;
		motor[leftMotor] = -60;
	}
	//stop
	motor[rightMotor] = 0;
	motor[leftMotor] = 0;
	wait1Msec(250);
}

//move foward to clear starting box
void clearStart()
{
	//Clear Encoders
	nMotorEncoder[rightMotor] = 0;

	//move foward for 3 secs to leave starting box
	motor[rightMotor] = 60;
	motor[leftMotor] = 60;
	wait1Msec(3000);
}

task main()
{
	for (j=1;j<6;j++)
	{
		clearStart();
		fowardToLine(j);
		moveBack();
	}

}
