#pragma config(Sensor, S2,     compass,        sensorVirtualCompass)
#pragma config(Sensor, S3,     light,          sensorLightActive)
#pragma config(Sensor, S4,     sonar,          sensorSONAR)
#pragma config(Motor,  motorB,          motorLeft,     tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          motorRight,    tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
// Virtual World Companion Tables 2.4 w/ RemBot

task main()
{
	wait1Msec(1000);

	// Move Foward to Middle of Maze
	nMotorEncoder[motorLeft] = 0;
	nMotorEncoder[motorRight] = 0;

	while(nMotorEncoder[motorLeft]<1440 || nMotorEncoder[motorRight]<1440)
	{
		motor[motorLeft] = 60;
		motor[motorRight] = 60;
		wait1Msec(50);
	}

		motor[motorLeft] = 0;
		motor[motorRight] = 0;
		wait1Msec(1000);

	// First Left Turn

	nMotorEncoder[motorLeft] = 0;
	nMotorEncoder[motorRight] = 0;

	while(nMotorEncoder[motorLeft]<160)
	{
		motor[motorLeft] = 60;
		motor[motorRight] = -60;
		wait1Msec(50);
	}

		motor[motorLeft] = 0;
		motor[motorRight] = 0;
		wait1Msec(1000);

	// Move Foward Again - Through Middle of Maze
	nMotorEncoder[motorLeft] = 0;
	nMotorEncoder[motorRight] = 0;

	while(nMotorEncoder[motorLeft]<1550 || nMotorEncoder[motorRight]<1550)
	{
		motor[motorLeft] = 60;
		motor[motorRight] = 60;
		wait1Msec(50);
	}

		motor[motorLeft] = 0;
		motor[motorRight] = 0;
		wait1Msec(1000);

	// First Right Turn
	nMotorEncoder[motorLeft] = 0;
	nMotorEncoder[motorRight] = 0;

	while(nMotorEncoder[motorRight]<160)
	{
		motor[motorLeft] = -60;
		motor[motorRight] = 60;
		wait1Msec(50);
	}

		motor[motorLeft] = 0;
		motor[motorRight] = 0;
		wait1Msec(1000);

	// Move Foward - Before Goal Entrance
	nMotorEncoder[motorLeft] = 0;
	nMotorEncoder[motorRight] = 0;

	while(nMotorEncoder[motorLeft]<1440 || nMotorEncoder[motorRight]<1440)
	{
		motor[motorLeft] = 60;
		motor[motorRight] = 60;
		wait1Msec(50);
	}

		motor[motorLeft] = 0;
		motor[motorRight] = 0;
		wait1Msec(1000);

	// Last Right Turn - Toward Goal Entrance
	nMotorEncoder[motorLeft] = 0;
	nMotorEncoder[motorRight] = 0;

	while(nMotorEncoder[motorRight]<160)
	{
		motor[motorLeft] = -60;
		motor[motorRight] = 60;
		wait1Msec(50);
	}

		motor[motorLeft] = 0;
		motor[motorRight] = 0;
		wait1Msec(1000);

	//Move Foward into the Goal
	nMotorEncoder[motorLeft] = 0;
	nMotorEncoder[motorRight] = 0;

	while(nMotorEncoder[motorLeft]<1000 || nMotorEncoder[motorRight]<1000)
	{
		motor[motorLeft] = 60;
		motor[motorRight] = 60;
		wait1Msec(50);
	}

		motor[motorLeft] = 0;
		motor[motorRight] = 0;
		wait1Msec(1000);



}
