#pragma config(Sensor, S1,     touchSensor,    sensorTouch)
#pragma config(Sensor, S2,     compassSensor,  sensorVirtualCompass)
#pragma config(Sensor, S3,     lightSensor,    sensorLightActive)
#pragma config(Sensor, S4,     sonarSensor,    sensorSONAR)
#pragma config(Motor,  motorB,          rightMotor,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          leftMotor,     tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//VW Obstacle Course using RemBot Curriculum Tables 2.4

task main()
{
	//Move Foward until obstacle touched
while(SensorValue(touchSensor) == 0)
	{
		motor[leftMotor] = 60;
		motor[rightMotor] = 60;
		wait1Msec(50);
	}

	//stop after hitting obstacle
	motor[leftMotor] = 0;
	motor[rightMotor] = 0;
	wait1Msec(500);

	//Back up
	/*motor[leftMotor] = -60;
	motor[rightMotor] = -60;
	wait1Msec(600);*/

	//turn left
	motor[leftMotor] = -60;
	motor[rightMotor]= 60;
	wait1Msec(650);


	//Move Foward
	motor[leftMotor] = 60;
	motor[rightMotor] = 60;
	wait1Msec(3000);

	//Follow Dark Line for certain distance
	nMotorEncoder[leftMotor] = 0;
	nMotorEncoder[rightMotor] = 0;

	while(nMotorEncoder[leftMotor] < 3400 && nMotorEncoder[rightMotor] < 3400)
	{
			if (SensorValue(lightSensor) < 45)
			{
				//sensor sees light, counter steer left
				motor[leftMotor] = 55;
				motor[rightMotor] = 10;

			}

			else
			{
				//sensor sees dark, counter steer right
				motor[leftMotor] = 10;
				motor[rightMotor] = 55;

			}

		}

		//Stop
		motor[leftMotor] = 0;
		motor[rightMotor] = 0;
		wait1Msec(1000);

	//Follow Dark Line for certain distance
	nMotorEncoder[leftMotor] = 0;
	nMotorEncoder[rightMotor] = 0;

	while(nMotorEncoder[leftMotor] < 1500 && nMotorEncoder[rightMotor] < 1500)
	{
			if (SensorValue(lightSensor) < 45)
			{
				//sensor sees light, counter steer left
				motor[leftMotor] = 10;
				motor[rightMotor] = 55;

			}

			else
			{
				//sensor sees dark, counter steer right
				motor[leftMotor] = 55;
				motor[rightMotor] = 10;

			}

		}

		//Stop
		motor[leftMotor] = 0;
		motor[rightMotor] = 0;
		wait1Msec(1000);




}
