#pragma config(Sensor, S1,     touchSensor,    sensorTouch)
#pragma config(Sensor, S2,     compassSensor,  sensorVirtualCompass)
#pragma config(Sensor, S3,     lightSensor,    sensorLightActive)
#pragma config(Sensor, S4,     sonarSensor,    sensorSONAR)
#pragma config(Motor,  motorA,          gripperMotor,  tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          rightMotor,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          leftMotor,     tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//Robo 500 1 Virtual World w/ remBot
/*+++++++++++++++++++++++++++++++++++++++++++++| Notes |++++++++++++++++++++++++++++++++++++++++++++++
Moving Forward
This program instructs your robot to move forward at full power for three seconds.
There is a two second pause at the beginning of the program.

Robot Model(s): NXT REMBOT

[I/O Port]          [Name]              [Type]                [Description]
Motor Port B        rightMotor          NXT Motor             Right side motor
Motor Port C        leftMotor           NXT Motor             Left side motor

----------------------------------------------------------------------------------------------------*/


//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
int i=0;

task main()
{
	wait1Msec(2000);						// Robot waits for 2000 milliseconds before executing program

	// Move forward at full power for 3 seconds
for (i=i+1;i<=8;i++)
	{
	motor[rightMotor] = 100;		  // Motor on motorB is run at full (100) power forward
	motor[leftMotor]  = 100;		  // Motor on motorC is run at full (100) power forward
	wait1Msec(4650);			        // Robot runs previous code for 3000 milliseconds before moving on

	motor[rightMotor] = 0;		    // Motor on motorB is turned off
	motor[leftMotor]  = 0;			  // Motor on motorC is turned off
	wait1Msec(1000);					    // Robot stops for 1 second

	motor[rightMotor] = -100;		  // Motor on motorB is run at full (100) power forward
	motor[leftMotor]  = 100;		  // Motor on motorC is run at full (100) power forward
	wait1Msec(545);

	motor[rightMotor] = 0;		    // Motor on motorB is turned off
	motor[leftMotor]  = 0;			  // Motor on motorC is turned off
	wait1Msec(1000);					    // Robot stops for 1 second
	}



	// Robot runs previous code for 3000 milliseconds before moving on
}												        // Program ends, and the robot stops
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
