#pragma config(Sensor, S1,     touch,          sensorTouch)
#pragma config(Motor,  motorB,          leftMotor,     tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//Robo 500 2 Virtual World w/ remBot

int i;

task main()
{
	wait1Msec(1000);						// Robot waits for 2000 milliseconds before executing program

	for (i=0; i<9;i=i+1)
	{
		while (SensorValue(touch)== 0)
		{
			motor(rightMotor) = 60;
			motor(leftMotor) = 60;
			wait1Msec(50);
		}
			motor(rightMotor) = 0;
			motor(leftMotor) = 0;
			wait1Msec(500);							// Robot stops for 1 second


			motor[rightMotor] = 60;			// Motor on motorB is run at full (100) power forward
			motor[leftMotor]	= -60;			// Motor on motorC is run at full (100) power forward
			wait1Msec(700);

			motor[rightMotor] = 0;				// Motor on motorB is turned off
			motor[leftMotor]	= 0;				// Motor on motorC is turned off
			wait1Msec(500);							// Robot stops for 1 second
	}

}
