#pragma config(Sensor, S2,     touch,          sensorTouch)
#pragma config(Sensor, S3,     light,          sensorLightActive)
#pragma config(Sensor, S4,     sonar,          sensorSONAR)
#pragma config(Motor,  motorB,          rightMotor,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          leftMotor,     tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//Robo Slalom Virtual World w/ remBot

void rightTurn()
{
	motor[rightMotor] = -60;		  // Motor on motorB is run at full (100) power forward
	motor[leftMotor]  = 60;		  // Motor on motorC is run at full (100) power forward
	wait1Msec(770);			        // Robot runs previous code for 3000 milliseconds before moving on

	motor[rightMotor] = 0;		    // Motor on motorB is turned off
	motor[leftMotor]  = 0;			  // Motor on motorC is turned off
	wait1Msec(1000);					    // Robot stops for 1 second
}

void leftTurn()
{
	motor[rightMotor] = 60;		  // Motor on motorB is run at full (100) power forward
	motor[leftMotor]  = -60;		  // Motor on motorC is run at full (100) power forward
	wait1Msec(770);			        // Robot runs previous code for 3000 milliseconds before moving on

	motor[rightMotor] = 0;		    // Motor on motorB is turned off
	motor[leftMotor]  = 0;			  // Motor on motorC is turned off
	wait1Msec(1000);					    // Robot stops for 1 second
}
void fowardTime (int t)
{
	motor[rightMotor] = 70;		  // Motor on motorB is run at full (100) power forward
	motor[leftMotor]  = 70;		  // Motor on motorC is run at full (100) power forward
	wait1Msec(t);

	motor[rightMotor] = 0;		    // Motor on motorB is turned off
	motor[leftMotor]  = 0;			  // Motor on motorC is turned off
	wait1Msec(1000);					    // Robot stops for 1 second
}

task main()
{

	wait1Msec(2000);						// Robot waits for 2000 milliseconds before executing program


	rightTurn();

	fowardTime (3000);

	leftTurn();

	fowardTime(5000);

	leftTurn();

	fowardTime(6000);

	rightTurn();

	fowardTime(4000);

	rightTurn ();

	fowardTime(6000);

	leftTurn ();

	fowardTime (4000);

	leftTurn ();

	fowardTime (6000);

	rightTurn();

	fowardTime (4000);





	}												        // Program ends, and the robot stops
