#pragma config(Sensor, S1,     touchSensor,    sensorTouch)
#pragma config(Sensor, S2,     compassSensor,  sensorVirtualCompass)
#pragma config(Sensor, S3,     lightSensor,    sensorLightActive)
#pragma config(Sensor, S4,     sonarSensor,    sensorSONAR)
#pragma config(Motor,  motorA,          gripperMotor,  tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          rightMotor,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          leftMotor,     tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//Robo 500 1 Virtual World w/ remBot
/*+++++++++++++++++++++++++++++++++++++++++++++| Notes |++++++++++++++++++++++++++++++++++++++++++++++

Robot Model(s): NXT REMBOT

[I/O Port]          [Name]              [Type]                [Description]
Motor Port B        rightMotor          NXT Motor             Right side motor
Motor Port C        leftMotor           NXT Motor             Left side motor

----------------------------------------------------------------------------------------------------*/


//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
int i=0;

task main()
{
	wait1Msec(500);

//Makes 4 laps around a square

for (i=i+1;i<=8;i++)
	{
	//Move foward
	motor[rightMotor] = 100;
	motor[leftMotor]  = 100;
	wait1Msec(4650);

	motor[rightMotor] = 0;
	motor[leftMotor]  = 0;

	//Turn right
	motor[rightMotor] = -100;
	motor[leftMotor]  = 100;
	wait1Msec(545);

	motor[rightMotor] = 0;
	motor[leftMotor]  = 0;
	wait1Msec(1000);
	}




}												        // Program ends, and the robot stops
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
