#pragma config(Sensor, S1,     touchSensor,    sensorTouch)
#pragma config(Sensor, S2,     compassSensor,  sensorVirtualCompass)
#pragma config(Sensor, S3,     lightSensor,    sensorLightActive)
#pragma config(Sensor, S4,     sonarSensor,    sensorSONAR)
#pragma config(Motor,  motorB,          leftMotor,     tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Table Bot 2 Challenge in VW with Rembot

//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
task main()
{
  wait1Msec(1000);          // The program waits for 2000 milliseconds before continuing.

  int threshold = 45;       /* found by taking a reading on both DARK and LIGHT    */
                            /* surfaces, adding them together, then dividing by 2. */

 while (true)
	{
    // sensor sees light:
    if(SensorValue(lightSensor) >= threshold)
    {
      // move foward:
      motor[leftMotor]  = 55;
      motor[rightMotor] = 55;
    }
    // move back and randomly turn:
    else
    {
      motor[leftMotor]  = -55;
      motor[rightMotor] = -55;
      wait1Msec(2000);

     	motor[leftMotor]  = -random(30);
      motor[rightMotor] = 30;
      wait1Msec(1000);
    }
	}
}
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
